### ISSUE TITLE
Not necessarily safe for production?

### ISSUE THREAD

**Issue by bschlenk** [just-boris/backbone-decorators#7]
Hi! 

This repo is not actively maintained and I will not be responding to issues directly any more.  

If you're interested in contributing and growing it, please open a few PRs that show the direction you want to take it and we can discuss.

Looks like you aren't responding to PRs anymore either. I just want to throw this out there, what isn't necessarily safe for production about this? Have you run into any issues while using these decorators? I read your backbone classes article and this was the solution I liked best.

**Comment by just-boris** [comment]
Hello! First of all, @benmccormick has transferred this repository to me. It is also true, that I am not maintaining this project too much, however it is safe to use in production.

I have some of these projects available in open-source: https://github.com/allure-framework/allure2/blob/master/allure-generator/src/main/javascript/decorators/index.js#L1
It works just well, but if you have any suggestions, or feature requests, I will be happy to discuss.

**Comment by bschlenk** [comment]
Thank you! That is good to know, I'm considering migrating some of my backbone views to use class syntax so it'll be great to be able to use this.
